<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NHS111.Contracts\NHS111.Contracts.csproj" />
    <ProjectReference Include="..\..\src\NHS111.Infrastructure\NHS111.Infrastructure.csproj" />
  </ItemGroup>

</Project>
